-- =========================================================
---------------------   "EventLog"     ---------------------
-- =========================================================
CREATE TABLE "EventLog" (
	"Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Created" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"EventType" VARCHAR(20),
	"Message" VARCHAR(2000)
);