UPDATE "Message" SET "Value" = 'Vi ćete biti odjavljeni...' WHERE "Key" = 'You will be loged out...' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Svi povezani uređaji će biti resetovani.' WHERE "Key" = 'You will reset all connected devices.' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Odštampana vrijednost' WHERE "Key" = 'Printed value' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Izmijeni poruku' WHERE "Key" = 'Edit message' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Zahtjevani iznos do' WHERE "Key" = 'Amount requested to' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Zahtjevani iznos od' WHERE "Key" = 'Amount requested from' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Štampaj i obriši zbirne vrijednosti.' WHERE "Key" = 'Print and clear totals' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Kovanice' WHERE "Key" = 'Coins' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Isplaćena vrijednost' WHERE "Key" = 'Dispensed value' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Prihvaćena vrijednost' WHERE "Key" = 'Accepted value' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Isprazni' WHERE "Key" = 'Empty' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Događaji neuspjeha' WHERE "Key" = 'Fail events' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Može da se iskoristi' WHERE "Key" = 'Can be redeemed' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Vrijednost' WHERE "Key" = 'Value' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Sada možete da koristite novu karticu za prijavu operatera.' WHERE "Key" = 'You can now use new card for operator login action.' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Uredi podešavanja' WHERE "Key" = 'Edit settings' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Konektovan na CMS' WHERE "Key" = 'Connected to CMS' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Konektovan na internet' WHERE "Key" = 'Connected to internet' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Evidencija događaja' WHERE "Key" = 'Event log' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Uređaj' WHERE "Key" = 'Device' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Prilagođavanje' WHERE "Key" = 'Customization' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Isplaćena vrijednost' WHERE "Key" = 'Dispensed value' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Dan počinje u kazinu' WHERE "Key" = 'Casino day starts' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Minimum kovanica mora biti veća od ili jednaka 0.' WHERE "Key" = 'Coins min must be greater than or equal to 0.' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Minimum tiketa mora biti veći ili jednak 0.' WHERE "Key" = 'Tickets min must be greater than or equal to 0.' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Minimum novčanica mora biti veće ili jednako 0.' WHERE "Key" = 'Bills min must be greater than or equal to 0.' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Minimum tiketa mora biti manji od ili jednak od tiket maksimuma.' WHERE "Key" = 'Tickets min must be less than or equal to tickets max.' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Minimum kovanica mora biti manji ili jednako maximalnom broju kovanica.' WHERE "Key" = 'Coins min must be less than or equal to coins max.' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Minimum novčanica mora biti manji ili jednak maksimalnom broju.' WHERE "Key" = 'Bills min must be less than or equal to bills max.' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Broj tiketa mora biti veći od 0.' WHERE "Key" = 'Tickets max must be greater than 0.' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Maksimalan broj kovanica mora biti veći od 0.' WHERE "Key" = 'Coins max must be greater than 0.' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Maksimalan broj novčanica mora biti veći od 0.' WHERE "Key" = 'Bills max must be greater than 0.' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Potrebno je popuniti polje ključa.' WHERE "Key" = 'The key field is required.' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Vrijeme početka dana mora biti validno vreme u formatu hh:mm.' WHERE "Key" = 'Day start time must be a valid time in the format hh:mm' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Početno vrijeme dana mora biti u formatu hh:mm' WHERE "Key" = 'Day start time must be in the format hh:mm' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Naziv lokacije je obavezan' WHERE "Key" = 'Location name is required' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Mora biti veće od 0' WHERE "Key" = 'Must be greater than 0' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Neispravan model uređaja' WHERE "Key" = 'Invalid device model' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Potrebna je vrsta štampača' WHERE "Key" = 'Printer type is required' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Nevažeći tip terminala.' WHERE "Key" = 'Invalid terminal type' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Nevažeći broj stavki' WHERE "Key" = 'Invalid number of items' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Kanali za izdavanje moraju biti između {0} i {1}' WHERE "Key" = 'Dispense channels must be between {0} and {1}' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Potrebna je vrijednost' WHERE "Key" = 'Value is required' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Tip uređaja je obavezan' WHERE "Key" = 'Device type is required' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = 'Lozinka je obavezna.' WHERE "Key" = 'Password is required.' AND "LanguageCode" = 'bs';
UPDATE "Message" SET "Value" = '' WHERE "Key" = '' AND "LanguageCode" = 'bs';

DELETE FROM "Message" where "Key" = 'Printing tequested at';
INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('3255d9e6-f1e3-469f-b150-ddcecdd1bf88', 1, 'bs', 'Printing requested at', 'Štampa zahtevana u');
INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('059e406d-1d9e-4aa0-91ec-5d3d55aa9e89', 1, 'us', 'Printing requested at', 'Printing requested at');