DELETE FROM "OperatorPermission" WHERE "OperatorId" = (select "Id" from "Operator" WHERE "Username" = 'admin');

INSERT INTO "OperatorPermission" ("Version","Guid","OperatorId","PermissionId") VALUES (1,'ad0ae7e2-bc11-471a-9230-ec4be0d49fb9',(select "Id" from "Operator" WHERE "Username" = 'admin'),(SELECT "Id" FROM "Permission" WHERE "Code" = 'BillAcceptor'));
INSERT INTO "OperatorPermission" ("Version","Guid","OperatorId","PermissionId") VALUES (1,'1b38215c-0103-4642-b50a-90e1bce2a4df',(select "Id" from "Operator" WHERE "Username" = 'admin'),(SELECT "Id" FROM "Permission" WHERE "Code" = 'BillDispenser'));
INSERT INTO "OperatorPermission" ("Version","Guid","OperatorId","PermissionId") VALUES (1,'4278b0c3-118d-4acc-a645-2267a5ca6bf0',(select "Id" from "Operator" WHERE "Username" = 'admin'),(SELECT "Id" FROM "Permission" WHERE "Code" = 'CoinDispenser'));
INSERT INTO "OperatorPermission" ("Version","Guid","OperatorId","PermissionId") VALUES (1,'da50c9ad-d77b-4ce8-b318-cf459157776e',(select "Id" from "Operator" WHERE "Username" = 'admin'),(SELECT "Id" FROM "Permission" WHERE "Code" = 'CardReader'));
INSERT INTO "OperatorPermission" ("Version","Guid","OperatorId","PermissionId") VALUES (1,'a1dc88c1-ad7d-4bba-979e-c757f9ed71f1',(select "Id" from "Operator" WHERE "Username" = 'admin'),(SELECT "Id" FROM "Permission" WHERE "Code" = 'MoneyService'));
INSERT INTO "OperatorPermission" ("Version","Guid","OperatorId","PermissionId") VALUES (1,'8da528b0-91d0-42ba-b663-003482c8fec6',(select "Id" from "Operator" WHERE "Username" = 'admin'),(SELECT "Id" FROM "Permission" WHERE "Code" = 'Reports'));
INSERT INTO "OperatorPermission" ("Version","Guid","OperatorId","PermissionId") VALUES (1,'246b8cc9-92f0-48eb-8be1-2c75a564e0e3',(select "Id" from "Operator" WHERE "Username" = 'admin'),(SELECT "Id" FROM "Permission" WHERE "Code" = 'Administration'));	
INSERT INTO "OperatorPermission" ("Version","Guid","OperatorId","PermissionId") VALUES (1,'c8cbe879-64ba-41ff-a44f-9a5ad68d406e',(select "Id" from "Operator" WHERE "Username" = 'admin'),(SELECT "Id" FROM "Permission" WHERE "Code" = 'Configuration'));
INSERT INTO "OperatorPermission" ("Version","Guid","OperatorId","PermissionId") VALUES (1,'0ad141f2-565f-48ff-8266-7ea1b38e82eb',(select "Id" from "Operator" WHERE "Username" = 'admin'),(SELECT "Id" FROM "Permission" WHERE "Code" = 'Shutdown'));
INSERT INTO "OperatorPermission" ("Version","Guid","OperatorId","PermissionId") VALUES (1,'aa43085f-fbcf-4eb6-932f-27c1e7e0e4e6',(select "Id" from "Operator" WHERE "Username" = 'admin'),(SELECT "Id" FROM "Permission" WHERE "Code" = 'Maintenance'));
