DROP TABLE "MoneyStatusTransaction";

CREATE TABLE "MoneyStatusTransaction" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Version" INTEGER NOT NULL,
    "Guid" CHAR(36) NOT NULL,
	"Created" TIMESTAMP,
	"CreatedBy" VARCHAR(200),
	"Updated" TIMESTAMP,
	"UpdatedBy" VARCHAR(200),
	"Timestamp" TIMESTAMP,
    "TransactionKind" VARCHAR(50) NOT NULL,
    "Amount" DECIMAL(18, 2) NOT NULL,
    "Currency" VARCHAR(3) NOT NULL,
    "StatusId" INTEGER NOT NULL,
    "TransactionTypeId" INTEGER NOT NULL,
    "OldDispenserBillCountStatus" VARCHAR(2048),
    "NewDispenserBillCountStatus" VARCHAR(2048),
    "OldAcceptorBillCountStatus" VARCHAR(2048),
    "NewAcceptorBillCountStatus" VARCHAR(2048),
    "UserEmail" VARCHAR(255),
    "Username" VARCHAR(255)
);

ALTER TABLE "MoneyStatusTransaction"
ADD CONSTRAINT FK_MoneyStatusTransaction_StatusId FOREIGN KEY ("StatusId") REFERENCES "TransactionStatus" ("Id");

ALTER TABLE "MoneyStatusTransaction"
ADD CONSTRAINT FK_MoneyStatusTransaction_TransactionTypeId FOREIGN KEY ("TransactionTypeId") REFERENCES "TransactionType" ("Id");
