CREATE TABLE "IdentificationCard" (
	"Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Version" INTEGER NOT NULL,
	"Guid" CHAR(36) NOT NULL,
    "Created" TIMESTAMP,
	"CreatedBy" VARCHAR(200),
	"Updated" TIMESTAMP,
	"UpdatedBy" VARCHAR(200),
	"SerialNumber" VARCHAR(200) NOT NULL,
	"OperatorId" INTEGER NOT NULL,
	"IssuedBy" VARCHAR(200),
	"IssuedAt" VARCHAR(200),
	"ValidFrom" DATE NOT NULL,
	"ValidTo" DATE,
	FOREIGN KEY ("OperatorId") REFERENCES "Operator" ("Id")
);

ALTER TABLE "IdentificationCard"
ADD CONSTRAINT PK_IdentificationCard PRIMARY KEY ("Id");