CREATE TABLE "TicketType" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" VARCHAR(50) NOT NULL,
    "Description" VARCHAR(255)
);

CREATE TABLE "Ticket" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Version" INTEGER NOT NULL,
    "Guid" CHAR(36) NOT NULL,
	"Created" TIMESTAMP,
	"CreatedBy" VARCHAR(200),
	"Updated" TIMESTAMP,
	"UpdatedBy" VARCHAR(200),
    "TicketTypeId" INTEGER NOT NULL,
    "Number" VARCHAR(255) NOT NULL,
    "Barcode" VARCHAR(255) NOT NULL,
    "Amount" DECIMAL(18, 2) NOT NULL,
    "Currency" VARCHAR(3) NOT NULL,
    "IsLocal" BOOLEAN NOT NULL,
    "IsPrinted" BOOLEAN NOT NULL,
    "IsRedeemed" BOOLEAN NOT NULL,
    "IsStacked" BOOLEAN NOT NULL,
    "PrintingRequestedAt" TIMESTAMP NOT NULL,
    "PrintingCompletedAt" TIMESTAMP,
    "DaysValid" INTEGER NOT NULL,
    "ExpirationDateTime" TIMESTAMP NOT NULL
);

ALTER TABLE "Ticket"
ADD CONSTRAINT FK_Ticket_TicketTypeId FOREIGN KEY ("TicketTypeId") REFERENCES "TicketType" ("Id");


CREATE TABLE "TransactionType" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" VARCHAR(50) NOT NULL,
    "Description" VARCHAR(255)
);


CREATE TABLE "TransactionStatus" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" VARCHAR(50) NOT NULL,
    "Description" VARCHAR(255)
);    
    


CREATE TABLE "Transaction" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Version" INTEGER NOT NULL,
    "Guid" CHAR(36) NOT NULL,
	"Created" TIMESTAMP,
	"CreatedBy" VARCHAR(200),
	"Updated" TIMESTAMP,
	"UpdatedBy" VARCHAR(200),
    "TransactionKind" VARCHAR(50) NOT NULL,
    "ProcessingStarted" TIMESTAMP NOT NULL,
    "ProcessingEnded" TIMESTAMP,
    "AmountRequested" DECIMAL(18, 2) NOT NULL,
    "Amount" DECIMAL(18, 2) NOT NULL,
    "Currency" VARCHAR(3) NOT NULL,
    "StatusId" INTEGER NOT NULL,
    "TransactionTypeId" INTEGER NOT NULL,
    "Description" VARCHAR(255),
    "ExternalReference" VARCHAR(255),
    "TicketId" INTEGER
);

ALTER TABLE "Transaction"
ADD CONSTRAINT FK_Transaction_StatusId FOREIGN KEY ("StatusId") REFERENCES "TransactionStatus" ("Id");

ALTER TABLE "Transaction"
ADD CONSTRAINT FK_Transaction_TransactionTypeId FOREIGN KEY ("TransactionTypeId") REFERENCES "TransactionType" ("Id");


CREATE TABLE "DispenserBillTransactionItem" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Version" INTEGER NOT NULL,
    "Created" TIMESTAMP,
	"CreatedBy" VARCHAR(200),
	"Updated" TIMESTAMP,
	"UpdatedBy" VARCHAR(200),
    "TransactionId" INTEGER NOT NULL,
    "CassetteNumber" INTEGER NOT NULL,
    "BillDenomination" INTEGER NOT NULL,
    "BillCountRequested" INTEGER NOT NULL,
    "BillCountRejected" INTEGER,
    "BillCountDispensed" INTEGER
);

ALTER TABLE "DispenserBillTransactionItem"
ADD CONSTRAINT FK_DispenserBillTransactionItem_TransactionId FOREIGN KEY ("TransactionId") REFERENCES "Transaction" ("Id");


