CREATE TABLE "TicketTypeDetail" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" VARCHAR(50) NOT NULL,
    "Description" VARCHAR(255),
    CONSTRAINT PK_TICKETTYPEDETAIL PRIMARY KEY ("Id")
);

ALTER TABLE "Transaction" ADD "TicketTypeDetailId" INTEGER;



ALTER TABLE "Transaction" ADD "TicketTypeId" INTEGER;

ALTER TABLE "Ticket"
ADD CONSTRAINT FK_Transaction_TicketTypeId FOREIGN KEY ("TicketTypeId") REFERENCES "TicketType" ("Id");


UPDATE "TicketType" SET "Code" = 'MonroeCashConfirmation' WHERE "Code" = 'CashConfirmation';
INSERT INTO "TicketType" ("Id","Code","Description") VALUES (3,'BetboxTicket','Betbox integration');






INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('9a3c04c0-9576-40ad-b7fb-614b39da1dd3', 1, 'bs', 'Redeem betbox ticket', 'Isplatite betbox tiket');
INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('94a3e52f-da05-40d7-805c-f65769cf1e5a', 1, 'us', 'Redeem betbox ticket', 'Redeem betbox ticket');

INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('635e2bb7-524c-4be3-beb3-b6b73d9030d0', 1, 'bs', 'Do you want to apply the voucher to the device credit?', 'Da li želite isplatiti vaučer na kredit uređaja?');
INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('e1418d1e-a07a-4efd-bb37-71eee83f38a0', 1, 'us', 'Do you want to apply the voucher to the device credit?', 'Do you want to apply the voucher to the device credit?');

INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('e1788f13-8d9c-4a7c-8883-45a92832cf60', 1, 'bs', 'Your transaction was successful', 'Transakcija je uspješna.');
INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('0af6be40-f672-4ae1-b13a-76dc3c054e47', 1, 'us', 'Your transaction was successful', 'Your transaction was successful');

INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('fb5d6289-60f5-45ab-8697-d28619f55b25', 1, 'bs', 'Transaction complete', 'Transakcija završena');
INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('4df3edce-c953-45ce-a36d-59646ed54360', 1, 'us', 'Transaction complete', 'Transaction complete');

INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('6807295a-1cab-49d6-becd-60823ebafe03', 1, 'bs', 'Transaction not completed', 'Transakcija neuspješna');
INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('265e7758-ff88-4d4e-9fb6-e813ef887421', 1, 'us', 'Transaction not completed', 'Transaction not completed');

INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('3bd914db-31cf-470d-b140-650d1c67746d', 1, 'bs', 'Please try again. Your transaction was unsuccessful.', 'Molimo Vas pokušajte ponovo. Vaša transakcija nije uspjela.');
INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('c2a044a6-3c82-40ea-9edf-2719ffda473c', 1, 'us', 'Please try again. Your transaction was unsuccessful.', 'Please try again. Your transaction was unsuccessful.');

INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('4f3fdee6-1526-4f7c-a197-919274ddb939', 1, 'bs', 'Continue', 'Nastavite');
INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('33849540-2145-432b-bb49-3ef91835938d', 1, 'us', 'Continue', 'Continue');

INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('e320faa8-fd4b-410b-a133-4be7aef3e5d5', 1, 'bs', 'We are preparing your transaction.', 'Transakcija u toku.');
INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('435b0a90-5e34-456c-90d1-1aa050dba161', 1, 'us', 'We are preparing your transaction.', 'We are preparing your transaction.');

INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('5bd62e79-1cb7-422e-9702-9fdf0467eb92', 1, 'bs', 'Amount to withdraw', 'Iznos za isplatu');
INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('b557c7c1-4e4d-44cd-8e7d-80d8c556c912', 1, 'us', 'Amount to withdraw', 'Amount to withdraw');

INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('3283d2f3-a70c-45fb-810c-f55d8a69bd29', 1, 'bs', 'Please scan the bar code', 'Molimo Vas skenirajte barkod');
INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('9ef14cd2-8aff-474c-8494-70f274434e98', 1, 'us', 'Please scan the bar code', 'Please scan the bar code');

INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('52facd1d-2964-4ff2-b92c-48b52f04a68a', 1, 'bs', 'One moment, please', 'Molimo Vas sačekajte');
INSERT INTO "Message" ("Guid", "Version", "LanguageCode", "Key", "Value") VALUES ('95028163-4361-48f4-9218-09fc293853c1', 1, 'us', 'One moment, please', 'One moment, please');

