CREATE TABLE "ParcelLockerShipmentStatus" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" VARCHAR(50) NOT NULL,
    "Description" VARCHAR(255)
);

CREATE TABLE "PostalServiceLocation" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Version" INTEGER NOT NULL,
    "Guid" CHAR(36) NOT NULL,
	"Created" TIMESTAMP,
	"CreatedBy" VARCHAR(200),
	"Updated" TIMESTAMP,
	"UpdatedBy" VARCHAR(200),
    "PostalService" VARCHAR(200) NOT NULL,
    "ContactNumber" VARCHAR(200),
    "LocationType" VARCHAR(50) NOT NULL,
    "ForSending" BOOLEAN DEFAULT TRUE,
    "ForReceiving" BOOLEAN DEFAULT TRUE,
    "Longitude" DECIMAL(9, 6) NOT NULL,
    "Latitude" DECIMAL(9, 6) NOT NULL,
    "StreetName" VARCHAR(255),
    "StreetNumber" VARCHAR(50),
    "PostalCode" VARCHAR(50),
    "City" VARCHAR(255),
    "Country" VARCHAR(255)
);

CREATE TABLE "ParcelLockerShipment" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Version" INTEGER NOT NULL,
    "Guid" CHAR(36) NOT NULL,
	"Created" TIMESTAMP,
	"CreatedBy" VARCHAR(200),
	"Updated" TIMESTAMP,
	"UpdatedBy" VARCHAR(200),

    "ShipmentStatusId" INTEGER,
    "PaymentRequired" BOOLEAN,
    "Amount" DECIMAL(18, 2),
    "Currency" VARCHAR(3),
    "ParcelLocker" VARCHAR(100),
    "PostalService" VARCHAR(100),
    "Timestamp" TIMESTAMP,
    "Barcode" VARCHAR(32),
    "RegistrationNumber" BIGINT,
    "LockerAccessCode" BIGINT,
    "CreatedByCourierId" VARCHAR(50),
    "UpdatedByCourierId" VARCHAR(50),
    "ExpirationDate" TIMESTAMP,

    "LocationType" VARCHAR(50),
    "StreetName" VARCHAR(255),
    "StreetNumber" VARCHAR(50),
    "City" VARCHAR(255),
    "PostalCode" VARCHAR(50),
    "Country" VARCHAR(255),
    "SenderFirstName" VARCHAR(255),
    "SenderLastName" VARCHAR(255),
    "SenderPhoneNumber" VARCHAR(255),
    "RecieverFirstName" VARCHAR(255),
    "RecieverLastName" VARCHAR(255),
    "RecieverPhoneNumber" VARCHAR(255)
);

ALTER TABLE "Transaction" ADD "ParcelLockerShipmentId" INTEGER;
ALTER TABLE "Transaction" ADD "ParcelLockerId" VARCHAR(100);

ALTER TABLE "Transaction" ADD CONSTRAINT FK_Transaction_ParcelLockerShipmentId FOREIGN KEY ("ParcelLockerShipmentId") REFERENCES "ParcelLockerShipment" ("Id");

ALTER TABLE "ParcelLockerShipment" ADD CONSTRAINT FK_ParcelLockerShipment_StatusId FOREIGN KEY ("ShipmentStatusId") REFERENCES "ParcelLockerShipmentStatus" ("Id");