

ALTER TABLE "Operator"
DROP "Level";

ALTER TABLE "Operator"
DROP "Number";

ALTER TABLE "Operator"
ADD "Remarks" BLOB SUB_TYPE TEXT;

ALTER TABLE "Operator"
ADD "Email" VARCHAR(200);

ALTER TABLE "Operator"
ADD "Username" VARCHAR(200);

ALTER TABLE "Operator"
ADD "PasswordSalt" VARCHAR(200);

ALTER TABLE "Operator"
ADD "IsActive" BOOLEAN DEFAULT TRUE;

--=====================================================================================

CREATE TABLE "IdentificationCardStatus" (
	"Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Code" VARCHAR(500) NOT NULL,
	"Description" VARCHAR(1000)
);

ALTER TABLE "IdentificationCardStatus"
ADD CONSTRAINT PK_IdentificationCardStatus PRIMARY KEY ("Id");

--=====================================================================================

ALTER TABLE "IdentificationCard"
ADD "Remarks" VARCHAR(32765);

ALTER TABLE "IdentificationCard"
ADD "LastStatusChange" TIMESTAMP;

ALTER TABLE "IdentificationCard"
ADD "IdentificationCardStatusId" INTEGER;

ALTER TABLE "IdentificationCard"
ADD CONSTRAINT FK_IdentificationCardStatus
FOREIGN KEY ("IdentificationCardStatusId") REFERENCES "IdentificationCardStatus" ("Id");

--=====================================================================================

CREATE TABLE "Permission" (
	"Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Code" VARCHAR(500) NOT NULL,
	"Description" VARCHAR(1000)
);

ALTER TABLE "Permission"
ADD CONSTRAINT PK_Permission PRIMARY KEY ("Id");

--=====================================================================================

CREATE TABLE "OperatorPermission" (
	"Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Version" INTEGER NOT NULL,
	"Guid" CHAR(36) NOT NULL,
    "Created" TIMESTAMP,
	"CreatedBy" VARCHAR(200),
	"Updated" TIMESTAMP,
	"UpdatedBy" VARCHAR(200),
	"OperatorId" INTEGER NOT NULL,
	"PermissionId" INTEGER NOT NULL,
	FOREIGN KEY ("OperatorId") REFERENCES "Operator" ("Id"),
	FOREIGN KEY ("PermissionId") REFERENCES "Permission" ("Id")
);

ALTER TABLE "OperatorPermission"
ADD CONSTRAINT PK_OperatorPermission PRIMARY KEY ("Id");