#!/bin/bash
systemctl daemon-reload

systemctl restart firebird5.0

/etc/flyway/flyway migrate -configFiles=/etc/flyway/monroe-flyway.toml

systemctl enable monroe-backbone
systemctl restart monroe-backbone
